### ISSUE TITLE
[REQUEST] add pkgx 'toolbox'

### ISSUE THREAD

**Issue by mabequinho** [Malix-off/awesome_atomic#54]
> What is pkgx?
> pkgx is a single, standalone binary that can run anything.

> Zero System Impact
> We don’t install packages. We cache them. Just like npx caches & executes node packages, pkgx caches everything else (including npx).

https://pkgx.sh/

**Comment by Malix-off** [comment]
Do not hesitate to make the associated pull request (and also [link it to that issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
